### ISSUE TITLE
Can't run the project: `ReferenceError: window is not defined`

### ISSUE THREAD

**Issue by aasutossh** [algolia/unified-instantsearch-ecommerce#157]
Forked, npm installed, npm run start results in errors: 
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ReferenceError: window is not defined
```
```
ERROR in ./src/components/Panel.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/components/Panel.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ReferenceError: window is not defined
    at Object.<anonymous> (C:\laragon\www\algolia\unified-instantsearch-ecommerce\/postcss.config.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at module.exports (C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\cosmiconfig\node_modules\import-fresh\index.js:28:9)
    at loadJs (C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\cosmiconfig\dist\loaders.js:9:18)
    at Explorer.loadFileContent (C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\cosmiconfig\dist\createExplorer.js:230:12)
    at C:\laragon\www\algolia\unified-instantsearch-ecommerce\node_modules\cosmiconfig\dist\createExplorer.js:252:21
 @ ./src/components/Panel.scss 2:26-183 43:4-64:5 46:18-175
 @ ./src/components/Panel.js
 @ ./src/components/Refinements.js
 @ ./src/components/index.js
 @ ./src/App.js
 @ ./src/index.js
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./public/index.ejs] 22.5 KiB {HtmlWebpackPlugin_0} [built]
i ｢wdm｣: Failed to compile.
```

**Comment by longjasonm** [comment]
I also ran into this issue. Using Node 12.20. Installed and ran using `yarn` and did not run into the issue.
